### ISSUE TITLE
Removing ignored app does not remove it from list

### ISSUE THREAD

**Issue by cweiske** [zhaobao/AppsMonitor#3]
When I go to settings ->  ignored apps and I click the "x" to remove it, it stays in the list.

In reality it gets removed, but the list view does not seem to be updated.
When I go back and then re-open the ignored apps list, the app is really gone.

**Comment by zhaobao** [comment]
@cweiske  Thanks for your feedback. The list refresh sync automatically. There is no need to restart app. You can just refresh the list by pull down.
