### ISSUE TITLE
Availability at f-droid.org

### ISSUE THREAD

**Issue by cweiske** [zhaobao/AppsMonitor#4]
I would like to see this app on f-droid.org. It is an Android app store that only lists open source software, and builds the apks on their own.

Would you be ok with me submitting a "request for packaging" on the f-droid issue tracker? (See https://f-droid.org/en/issues/)

**Comment by IzzySoft** [comment]
@cweiske even if the author agreed, F-Droid would not. The app comes with several proprietary libraries: Firebase, GMS and AppsFlyer Analytics. I've just added it to my repo for your convenience (should turn up with tomorrow's sync) – though I wish @zhaobao would remove those libraries. They don't go well with his promise never to collect the users' data.

**Comment by zhaobao** [comment]
@IzzySoft  Thanks for you suggestion, i just release a new version, remove Firebase and Appsflyer from the source code and fixed some gradle problem

**Comment by IzzySoft** [comment]
@zhaobao Thanks – that's great! My library scanner confirmed the 3 are gone (I've added your app [to my repo](https://apt.izzysoft.de/fdroid/index/apk/timeline.lizimumu.com.t) around the time I created above comment, the update should show up there with the next sync in half a day).

As the "offending libraries" are gone now, I've [created a Request For Packaging](https://gitlab.com/fdroid/rfp/issues/1179) (RFP), linking here for confirmation you agree with that. You might wish to setup [Fastlane file structure](https://gitlab.com/snippets/1895688) (to provide screenshots and maintain summary/description here); if you do so, please drop me a note to update the RFP accordingly.

If you wonder why I "unframed" your screenshots in my repo: I have in mind that people view them on their phones, where framing "wastes" valuable space and make it harder to see details on the screenshots themselves. But that's my personal opinion, YMMV :wink:

**Comment by IzzySoft** [comment]
PS: cool side-effect, the app size went down to half of what it had been before :smile:

**Comment by IzzySoft** [comment]
@cweiske can you please [take a look at this](https://gitlab.com/fdroid/rfp/-/issues/1179#note_305125167)? Seems there are some remains requiring some Google API key. Any hints on how to (get around | get rid of) that? Thanks!

**Comment by cweiske** [comment]
That's more for @zhaobao and not for me.

**Comment by IzzySoft** [comment]
Ooops… true, my bad – apologies! Guess I had too many issues today :rofl:

**Comment by zhaobao** [comment]
> While building project,
> 
> ERROR :- File google-services.json is missing. The Google Services Plugin cannot function without it.
> 
> How i will get google-service.json file ? @AnyBody Help Me If You Know....

My bad, the repository is no logger supported. **But**, for your need, please go with "no-ads" branch

**Comment by IzzySoft** [comment]
@zhaobao umpf… does that mean we shall close the RFP at F-Droid again? Or would you be so kind to have a "no-ads" build flavor? F-Droid won't accept the following, taken from your `build.gradle`:

```gradle
    implementation 'com.google.android.gms:play-services-ads:18.3.0'

apply plugin: 'com.google.gms.google-services'
```

So in order to build your app, it would need a build flavor coming without that.

**Comment by IzzySoft** [comment]
Sorry, but without that we cannot include your app in F-Droid. I'll close the [corresponding RFP](https://gitlab.com/fdroid/rfp/-/issues/1179) then. Give us a ping should you still be interested and have a corresponding build flavor available, @zhaobao. Thanks!
