### ISSUE TITLE
Update AppsMonito

### ISSUE THREAD

**Issue by asylla19** [zhaobao/AppsMonitor#5]
I can't see the data consumption of the applications installed on my smartphone. How to update the application for android 10? 
Thank you in advance. 

![Screenshot_2019-09-27-23-18-53](https://user-images.githubusercontent.com/56895678/67331372-f84a8200-f51d-11e9-9c0b-c47ead3ed3e7.png)

**Comment by zhaobao** [comment]
@asylla19 Thanks for your feedback, i will fixed and release a new version

**Comment by asylla19** [comment]
Hello,
thank you for your answer. Just for information, when do you plan to update your application?
Thank you in advance.

**Comment by zhaobao** [comment]
@asylla19 Please a new release version 1.8.3

**Comment by asylla19** [comment]
thanks a lot
